### ISSUE TITLE
Remove installation of bcrypt in Charm code

### ISSUE THREAD

**Issue by Barteus** [canonical/dex-auth-operator#100]
BCrypt is installed during the run of the charm, which is a bad practice. 
https://github.com/canonical/dex-auth-operator/blob/041cabc7ab051b72b0f024fbfef3e77a32c14196/src/charm.py#L26

It is used to hash the password only. We can use other libraries to perform string hashing which does not require the installation of the additional package.

Additionally, packages installed this way are not scanned during the CVE scanning.

**Comment by i-chvets** [comment]
Added to be fixed.

**Comment by i-chvets** [comment]
Low priority.
