### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by grobbie** [canonical/dex-auth-operator#15]
Hi folks,
Please ensure that this repo has a license associated with it, concretely that there is a valid LICENSE file present. Please also consider adding license headers to all files as per [generally accepted best practices](https://softwareengineering.stackexchange.com/questions/317041/should-i-add-the-license-in-every-header-and-source-file/357796).
Thanks

**Comment by DomFleischmann** [comment]
All of our repositories should have a `LICENSE` file with the apache license.

And a header similar to [this](https://github.com/canonical/alertmanager-operator/blob/main/src/charm.py#L1) in each file.

Additionally we should add a flake8 check like [this](https://github.com/canonical/alertmanager-operator/blob/main/pyproject.toml#L32) to make sure we have the header in any future additions.
