### ISSUE TITLE
Create a ROCK for Dex for CKF 1.7

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/dex-auth-operator#172]
### What needs to get done

1. Create a dedicated repo for `dex-rock`
3. Create the `rockcraft.yaml` file
4. Copy our CI automation for building the image on every PR and when a PR is merged

### Why it needs to get done

In order for us to have our own built OCI Image for that component

### Progress

* [x] canonical/dex-auth-rocks#1
* implement CI: 
  * [x] manually triggered build and publish (canonical/dex-auth-rocks#2)
  * [ ] automate build and publish CI to trigger on pull request and merge to a protected branch

**Comment by orfeas-k** [comment]
Created another issue for the ROCK's CI https://github.com/canonical/dex-auth-rocks/issues/4, closing this one as completed.
