### ISSUE TITLE
Integrate Dex ROCK in CKF 1.8

### ISSUE THREAD

**Issue by ca-scribner** [canonical/dex-auth-operator#182]
### Context

We'd like to use the image from canonical/dex-auth-rocks#7 for CKF distributions

### What needs to get done

* once canonical/dex-auth-rocks#7 is complete, update this charm to use the image from canonical/dex-auth-rocks#7 
* test that image in the dex-auth charm w/a minimal kubeflow environment using auth

### Definition of Done

1. the updated image included in this repo's `gh:main` and published to `ch:latest/edge`

**Comment by ca-scribner** [comment]
closed by #183

**Comment by kimwnasptd** [comment]
@ca-scribner this issue should not be closed, since the image was not included in the `track/2.36` branch

cc @DnPlas who also reviewed
