### ISSUE TITLE
Published charm doesn't include a link to source code

### ISSUE THREAD

**Issue by mthaddon** [canonical/dex-auth-operator#29]
This charm is published on https://charmhub.io/dex-auth but doesn't include a link to the source code. This can be done by the charm author by visiting https://charmhub.io/dex-auth/listing and editing the "Project Homepage" field.

**Comment by i-chvets** [comment]
Done.
![Screenshot from 2022-10-19 09-03-12](https://user-images.githubusercontent.com/113444075/196698726-19f13818-b861-4193-bc9b-82c0dfdc6552.PNG)
