### ISSUE TITLE
hook failed: "oidc-client-relation-broken"

### ISSUE THREAD

**Issue by grobbie** [canonical/dex-auth-operator#38]
I'm gettting this `hook failed: "oidc-client-relation-broken"` error consistently with the latest/stable version of dex-auth, when executing a config change with the command `juju config dex-auth static-username="blah" static-password="blahblah"`.

It means that the new pod with the new configuration is never promoted to leader and the deployment is trapped in an broken state.

**Comment by agathanatasha** [comment]
I tried deploying latest stable dex auth and execute config change with the given command. There was no error and new pod was promoted to leader without issues. @grobbie Do you have more info on what's your set up and steps to reproduce this?

**Comment by grobbie** [comment]
Thanks I think this was related to the test environment which was underspecced, so i'll close this ticket. Sorry
