### ISSUE TITLE
Sidecar version of charm (current version in `main`) does not update config when `juju config` invoked

### ISSUE THREAD

**Issue by ca-scribner** [canonical/dex-auth-operator#45]
Charm currently does not update the actual dex-auth workload whenever a config change occurs at the charm level.  The charm correctly handles the config change, updating the underlying configmaps, etc., but the workload that mounts the configmap is not restarted.  This is similar to canonical/minio-operator#47.  This can be demonstrated by:
```bash
juju config dex-auth connectors="this config should not work"`
# charm will fire config-changed and configmap will update, but workload itself will not break as expected
kubectl delete pod DEX-AUTH-WORKLOAD-POD-NAME
# New pod will be created to replace the deleted pod, but it will go into a crash loop and we can see the reason is the connector config by looking at `kubectl logs NEW-POD`
```

**Comment by natalian98** [comment]
Fixed by https://github.com/canonical/dex-auth-operator/pull/62
