### ISSUE TITLE
Update prometheus and grafana libs

### ISSUE THREAD

**Issue by phvalguima** [canonical/dex-auth-operator#64]
Hi,

We are still using an outdated version of Prometheus and Grafana libs in this charm. Can we update it to a more recent version, to cover [gh#262](https://github.com/canonical/prometheus-k8s-operator/issues/262)?

**Comment by agathanatasha** [comment]
libs are updated in [this pr](https://github.com/canonical/dex-auth-operator/pull/62/). Closing this issue
