### ISSUE TITLE
dex-auth unit in error state after some time

### ISSUE THREAD

**Issue by aym-frikha** [canonical/dex-auth-operator#66]
Hello,

I deployed this bundle https://pastebin.canonical.com/p/vwW3YZ82fG/ and then configuring the public url for dex and oidc applications to be able to access kubeflow. Then without chaning anything in the charms, neither in the bundle, I got the following juju status output: https://pastebin.canonical.com/p/rCqwDpnpyC/ and dex become in error state with this log: https://pastebin.canonical.com/p/Rty3NKcskj/

**Comment by DnPlas** [comment]
Hi @aym-frikha, is this behaviour observed after a restart, or after leaving the deployment for a while, perhaps?

**Comment by misohu** [comment]
This will be fixed in dex-auth 2.31 which comes with kubeflow 1.6. Once this is published to stable we will close this issue

**Comment by DomFleischmann** [comment]
Given that 1.6 is our I will proceed to close this issue.
