### ISSUE TITLE
Disable static password login

### ISSUE THREAD

**Issue by pkluska** [canonical/dex-auth-operator#76]
Currently after installation we can configure the connectors and remove the user credentials. However, would it be possible to disable the static password login?

There is an option in dex config to do that -> https://github.com/dexidp/dex/blob/master/examples/config-dev.yaml#L137

I would expect something like

```bash
juju config dex-auth enablePasswordDB=false
```

Thanks

**Comment by DomFleischmann** [comment]
Hello @pkluska this is definitely an interesting feature. I will add it as an enhancement and a good first issue for someone to add.

**Comment by DnPlas** [comment]
Hi @pkluska, sorry for the late reply. Is the `enablepasswordDB` configuration option something you tried disabling in the connector's configuration?

**Comment by beliaev-maksim** [comment]
please refer to the comment in associated PR and follow up issue #130
