### ISSUE TITLE
How to use the patched version for 1.21

### ISSUE THREAD

**Issue by maxisacoder** [canonical/dex-auth-operator#9]
I have noticed #8 and https://github.com/dexidp/dex/issues/2082#issuecomment-818124478
since this patch has been merged, how can I use the newest version of `dex-auth` 

for now,
I try 

```
sudo microk8s juju upgrade-charm dex-auth

```

but got this

```
Added charm "cs:~kubeflow-charmers/dex-auth-107" to the model.
ERROR cannot upgrade application "dex-auth" to charm "cs:~kubeflow-charmers/dex-auth-107": would break relation "dex-auth:service-mesh istio-pilot:service-mesh"
```

**Comment by DomFleischmann** [comment]
The latest dex charm only works with the latest istio charms also, Therefore I would recommend you to just reinstall kubeflow with the new 1.3 release, it is available on microk8s 1.20/edge.
